apiVersion: v1
kind: Service
metadata:
  name: svctest
  labels:
    component: comptest
spec:
  type: NodePort
  ports:
    - targetPort: 8181
      port: 8181
      nodePort: 30081
  selector:
    component: comptest
