apiVersion: apps/v1
kind: Deployment
metadata:
  name: apptest
  labels:
    app: apptest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apptest
  template:
    metadata:
      name: apptest
      labels:
        app: apptest
    spec:
      containers:
        - name: apptest
          image: cmajda/trask-k8s-httppublisher:1.0.1
          ports:
            - containerPort: 8181
