# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
resources:
  repositories:
  - repository: MyGitHubToolsRepo # The name used to reference this repository in the checkout step
    type: github
    endpoint: Cmajda
    name: Cmajda/learning
    
trigger:
  branches:
    include:
      - master
  paths:
    include:
      - maint.tf

pool:
  vmImage: ubuntu-latest

stages:
- stage: Validate
  jobs:
  - job: Installterraform
    steps:
    - task: TerraformInstaller@0
      displayName: "Install Terraform"
      inputs:
        terraformVersion: '1.0.7'