image:
  name: harbor.trask.cz/dockerhub-proxy/hashicorp/terraform:light
  entrypoint:
    - "/usr/bin/env"
    - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

variables:
  PLAN: plan.tfplan
  PLAN_JSON: tfplan.json

cache:
  paths:
    - .terraform
    - .terraform.lock.hcl

before_script:
  - "echo Environment: $CI_COMMIT_REF_SLUG"
  - apk --no-cache add jq
  - rm -rf .terraform
  - terraform --version
  - terraform init
  - alias convert_report="jq -r '([.resource_changes[]?.change.actions?]|flatten)|{\"create\":(map(select(.==\"create\"))|length),\"update\":(map(select(.==\"update\"))|length),\"delete\":(map(select(.==\"delete\"))|length)}'"

stages:
  - validate
  - build

validate:
  rules:
    - changes:
        - "*.tf"
  tags:
    - kubernetes-root
  stage: validate
  script:
    - terraform validate

plan:
  rules:
    - changes:
        - "*.tf"
  dependencies:
    - validate
  tags:
    - kubernetes-root
  stage: build
  script:
    - terraform plan -out=$PLAN
    - "terraform show --json $PLAN | convert_report > $PLAN_JSON"
  artifacts:
    paths:
      - $PLAN
    reports:
      terraform: $PLAN_JSON
