apiVersion: apps/v1
kind: Deployment
metadata:
  name: logreader-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logreader
  template:
    metadata:
      labels:
        app: logreader
    spec:
      restartPolicy: Always
      containers:
        - name: logreader
          image: cmajda/trask-k8s-logreader:1.0.0
          resources: {}
